// <auto-generated />
using System;
using CartFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814100358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CartStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("cart_status");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("CartId")
                        .HasName("pk_cart_master");

                    b.HasIndex("CartStatus")
                        .HasDatabaseName("ix_cart_master_cart_status");

                    b.ToTable("cart_master", (string)null);
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("CartItemId")
                        .HasName("pk_cart_item");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_item_cart_id_product_id");

                    b.ToTable("cart_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("CategoryId")
                        .HasName("pk_category_master");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("ux_category_master_category_name");

                    b.ToTable("category_master", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Stationery",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Grocery",
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("grand_total");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_no");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_date");

                    b.HasKey("InvoiceId")
                        .HasName("pk_invoice_master");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_master_cart_id");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_master_invoice_no");

                    b.ToTable("invoice_master", (string)null);
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("InvoiceItemId")
                        .HasName("pk_invoice_item");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("product_name");

                    b.HasKey("ProductId")
                        .HasName("pk_product_master");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("CategoryId", "ProductName")
                        .IsUnique()
                        .HasDatabaseName("ux_product_category_id_product_name");

                    b.ToTable("product_master", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_price", "price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 20m,
                            ProductName = "Pen"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 100m,
                            ProductName = "Book"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 10m,
                            ProductName = "Pencil"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 60m,
                            ProductName = "Notebook"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 500m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 900m,
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 700m,
                            ProductName = "USB Drive"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 1200m,
                            ProductName = "Headphone"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 80m,
                            ProductName = "Rice"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 50m,
                            ProductName = "Sugar"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 120m,
                            ProductName = "Tea"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 200m,
                            ProductName = "Coffee"
                        });
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.CartItem", b =>
                {
                    b.HasOne("CartFlow.Api.Models.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_cart");

                    b.HasOne("CartFlow.Api.Models.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_product");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Invoice", b =>
                {
                    b.HasOne("CartFlow.Api.Models.Entities.Cart", "Cart")
                        .WithOne("Invoice")
                        .HasForeignKey("CartFlow.Api.Models.Entities.Invoice", "CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_cart");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.InvoiceItem", b =>
                {
                    b.HasOne("CartFlow.Api.Models.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_item_invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Product", b =>
                {
                    b.HasOne("CartFlow.Api.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Cart", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CartFlow.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
